### ISSUE TITLE
Error for Java Platform subproject

### ISSUE THREAD

**Issue by aSemy** [DanySK/publish-on-central#287]
I have a subproject that only has the [Java Platform plugin](https://docs.gradle.org/current/userguide/java_platform_plugin.html) applied.

I also create a publication

```kotlin
// ./modules/versions-platform/build.gradle.kts

publishing.publications.create<MavenPublication>("mavenJavaPlatform") {
  from(components["javaPlatform"])
}
```

When I add `id("org.danilopianini.publish-on-central") version "0.8.0"` I get an error

```none
Publication javaPlatformMaven has no jar with no  classifier, which is required for Maven Central.
You can either:
    - create a task that generates a jar without the correct classifier for publish-on-central to bind, or
    - bind yourself a jar with the right classifier as artifact for the publication, or
    - disable the automatic configuration of all Maven publications for Maven Central with:
        publishOnCentral {
            autoConfigureAllPublications.set(false)
        }
      then manually configure the publications you want on Central with
        publishing.publications.withType<MavenPublication>/* filter the ones you want*/ {
            configureForMavenCentral(publishOnCentral)
        }
```

The Java Platform plugin only produces a pom.xml that is marked as a POM - therefore Sonatype has no requirement for a JAR.

https://central.sonatype.org/publish/requirements/#supply-javadoc-and-sources

> Projects with packaging other than `pom` have to supply JAR files that contain Javadoc and sources. 

I'll try and disable this manually, but it would be nice if it worked by default :)

**Comment by DanySK** [comment]
Nice case. I will change the behavior of the software, if it detects a pom package it must not create ancillary archives.
You can roll back to 0.7.x, which did not have this behaviour, waiting for me to fix this.

If you have a repository I can reproduce this with, it'd be useful to integrate as regression test.
